name: Fusionsolar report
description: Fetches info about solar stations from fusionsolar and send them as a e-mail
branding:
  icon: sun
  color: yellow
inputs:
  user:
    description: Login user for fusionsolar
    required: true
  password:
    description: Password for the fusionsolar user
    required: true
  smtp_user:
    description: User for SMTP server to send the email
  smtp_passwd:
    description: Password for SMTP server to send the email
  smtp_server:
    description: SMTP server to send email
  smtp_destinations:
    description: List of emails to send the results separated by space
runs:
  using: composite
  steps:
    - name: Setup tor for proxying
      uses: tor-actions/setup-tor@64121bc84235ab7038224e8ce08601efdb9bd8d9 # main
      with:
        daemon: true
    - name: Get container tag
      shell: bash
      run: |
        echo CONTAINER_REF="$(cat "${{ github.action_path }}/version.txt")" >> $GITHUB_ENV
    - name: Hide secrets
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.user }}"
        echo "::add-mask::${{ inputs.password }}"
        echo "::add-mask::${{ inputs.smtp_user }}"
        echo "::add-mask::${{ inputs.smtp_passwd }}"
        echo "::add-mask::${{ inputs.smtp_server }}"
        echo "::add-mask::${{ inputs.smtp_destinations }}"
    - name: Run fusionsolar workflow in one go
      shell: bash
      run: |
        
        docker run -i \
          --dns=1.1.1.1 \
          --net=host \
          -e SELENIUM_PROXY_SERVER=localhost:9050 \
          -e FUSIONSOLAR_USER="${{ inputs.user }}" \
          -e FUSIONSOLAR_PASSWORD="${{ inputs.password }}" \
          -e SMTP_USER="${{ inputs.smtp_user }}" \
          -e SMTP_PASSWD="${{ inputs.smtp_passwd }}" \
          -e SMTP_SERVER="${{ inputs.smtp_server }}" \
          -e SMTP_DESTINATIONS="${{ inputs.smtp_destinations }}" \
          ghcr.io/lucasew/fusionsolar-bot:$CONTAINER_REF
