[project]
name = "fusionsolar-bot"
dynamic = ["version"]

dependencies = [
  "selenium",
  "sentry-sdk"
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[tool.hatch.build.targets.wheel]
packages = ["fusionsolar_bot"]

[tool.hatch.version]
path = "version.txt"
pattern = "^(?P<version>[^$]*)"

[project.scripts]
fusionsolar-bot = "fusionsolar_bot:main"
