name: Autorelease

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New tag version'
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
  schedule:
  - cron: '0 2 * * 6'   # saturday 2am
jobs:
  autorelease:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Login to registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ github.token }}

    - name: Install mise
      uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4

    - name: Try to build it
      run: |
        go build ./cmd/fusionsolar-bot

    - name: Make release if everything looks right
      if: github.event_name != 'pull_request'
      env:
        NEW_VERSION: ${{ github.event.inputs.new_version }}
      run: |
        if [[ ! -z "$NEW_VERSION" ]]; then
          git config user.name actions-bot
          git config user.email actions-bot@users.noreply.github.com
          NO_TAG=1 ./make_release "$NEW_VERSION"
          echo "New version: $(cat version.txt)" >> $GITHUB_STEP_SUMMARY
          echo "RELEASE_VERSION=$(cat version.txt)" >> $GITHUB_ENV
        fi

    - name: Create release
      if: github.event_name != 'pull_request' && env.RELEASE_VERSION != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ env.RELEASE_VERSION }}
        TITLE: Release ${{ env.RELEASE_VERSION }}
      run: |
        gh release create "$TAG" \
          --title "$TITLE" \
          --generate-notes \
          --notes-start-tag $(gh release list --limit 1 --json tagName -q .[].tagName)

    - name: Build and publish container
      if: github.event_name != 'pull_request' && env.RELEASE_VERSION != ''
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }} .
        docker tag ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }} ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
        docker push ghcr.io/${{ github.repository }}:latest
